<<: !include  common.yaml

substitutions:
  name: "ttgo-wmbus-rx"
  friendly_name: "TTGO WMBUS Receiver (T-Lora v2.1)"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: esphome.wmbus_reader
    version: "5.0"

esp32:
  board: ttgo-lora32-v21
  framework:
    type: esp-idf

output:
  - platform: gpio
    id: status_led
    pin: GPIO25

i2c:
  sda: GPIO21
  scl: GPIO22

display:
  - platform: ssd1306_i2c
    id: my_display
    model: "SSD1306 128x64"
    address: 0x3C
    pages: !include { file: pages.yaml }

spi:
  clk_pin: GPIO5
  mosi_pin: GPIO27
  miso_pin: GPIO19

wmbus_radio:
  radio_type: SX1276
  cs_pin: GPIO18
  reset_pin: GPIO23
  irq_pin: GPIO33

<<: !include meters.yaml
